---
- meta: end_play
  when: (ansible_distribution != "Cumulus Linux" and ansible_distribution_major_version != "3")

- name: Check for replay (/opt/switch_done exists)
  stat:
    path: /opt/switch_done
  register: switch_done

- name: Configuring switch
  command: "{{ item }}"
  with_items:
    - "net add bridge {{ bridge_name }}"
    - "net add bridge {{ bridge_name }} ip address {{ prod_ip_addr }}/{{ prod_cidr_mask }}"
    - "net add bridge {{ bridge_name }} ports {{ bridge_ports }}"
    - "net commit"
  when:
    - switch_done.stat.exists != True

- name: Set replay protection (/opt/switch_done)
  file:
    path: /opt/switch_done
    state: touch
    owner: root
    group: root
    mode: '0744'
  when:
    - switch_done.stat.exists != True
...