---
- name: "restart rngd"
  systemd:
    name: rngd.service
    state: restarted
    enabled: yes
  
- name: "reload NetworkManager"
  systemd:
    name: NetworkManager.service
    state: reloaded
    enabled: yes

- name: "restart NetworkManager"
  systemd:
    name: NetworkManager.service
    state: restarted
    enabled: yes
...
