---
all:
  children:
# Server infrastructure 
    service_routers:
      hosts:
        r1:
          ansible_host: 192.168.11.100
    service_switches:
      hosts:
        sw1:
          ansible_host: 192.168.11.101
        sw2:
          ansible_host: 192.168.11.102
    service_mon_servers:
      hosts:
        mon:
          ansible_host: 192.168.11.105
    service_auth_servers:
      hosts:
        auth1:
          ansible_host: 192.168.11.103
        auth2:
          ansible_host: 192.168.11.104
    service_storage_servers:
      hosts:
        pcm1:
          ansible_host: 192.168.11.110
        pcm2:
          ansible_host: 192.168.11.111
        pcm3:
          ansible_host: 192.168.11.112
# Client infrastructure          
    client_routers:
      hosts:
        r2:
          ansible_host: 192.168.11.120
    client_switches:
      hosts:
        sw3:
          ansible_host: 192.168.11.121
    client_servers:
      hosts:
        srv1:
          ansible_host: 192.168.11.122
    client_workstations:
      hosts:
        ws1:
          ansible_host: 192.168.11.123
...